### PR TITLE
Fourth updated: tests automated generated by EVOSUITE.

### PR DESCRIPTION
**Pull request by LuanTa-CSUN**
Please refer to Strman_ESTest.java for tests automated generated by EVOSUITE.
Other diffs were pushed mainly for illustrated purpose.

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @shenhuang

**Review by shenhuang — COMMENTED** [review]
I do understand how EvoSuit generates the test cases. From their open source documentation I realize it generates the cases with Genetic Algorithms. But was the target generated based on the code description or based on the code itself? It does maximizes branch coverage that I know how they would do it, but how would they understand the operation logic of the code?

If the test based on the code behavior itself, would they be missing logical flaws in the code if they were never implemented correctly? Other wise how does their algorithm interpret these operations? I have tried to Google online for the result and except their source code file I have not yet found any documentation that answers my question.

**Review by shenhuang — COMMENTED** [review]
I do understand how EvoSuit generates the test cases. From their open source documentation I realize it generates the cases with Genetic Algorithms. But was the target generated based on the code description or based on the code itself? It does maximizes branch coverage that I know how they would do it, but how would they understand the operation logic of the code?

If the test based on the code behavior itself, would they be missing logical flaws in the code if they were never implemented correctly? Other wise how does their algorithm interpret these operations? I have tried to Google online for the result and except their source code file I have not yet found any documentation that answers my question.

**Review by shenhuang — COMMENTED** [review]
I do understand how EvoSuit generates the test cases. From their open source documentation I realize it generates the cases with Genetic Algorithms. But was the target generated based on the code description or based on the code itself? It does maximizes branch coverage that I know how they would do it, but how would they understand the operation logic of the code?

If the test based on the code behavior itself, would they be missing logical flaws in the code if they were never implemented correctly? Other wise how does their algorithm interpret these operations? I have tried to Google online for the result and except their source code file I have not yet found any documentation that answers my question.

**Review by shenhuang — COMMENTED** [review]
I do understand how EvoSuit generates the test cases. From their open source documentation I realize it generates the cases with Genetic Algorithms. But was the target generated based on the code description or based on the code itself? It does maximizes branch coverage that I know how they would do it, but how would they understand the operation logic of the code?

If the test based on the code behavior itself, would they be missing logical flaws in the code if they were never implemented correctly? Other wise how does their algorithm interpret these operations? I have tried to Google online for the result and except their source code file I have not yet found any documentation that answers my question.

**Comment by LuanTa-CSUN** [comment]
I think your question are really interesting. Unfortunately, so far I focused on trying to get EVOSUITE work properly and I didn't have time to dive deeper to those kind of concern yet.
However, on the homepage of EVOSUITE (http://www.evosuite.org/ ) if you scroll down, there are some interesting papers and documents you may want to look at.

**Comment by LuanTa-CSUN** [comment]
I think your question are really interesting. Unfortunately, so far I focused on trying to get EVOSUITE work properly and I didn't have time to dive deeper to those kind of concern yet.
However, on the homepage of EVOSUITE (http://www.evosuite.org/ ) if you scroll down, there are some interesting papers and documents you may want to look at.

**Comment by LuanTa-CSUN** [comment]
I think your question are really interesting. Unfortunately, so far I focused on trying to get EVOSUITE work properly and I didn't have time to dive deeper to those kind of concern yet.
However, on the homepage of EVOSUITE (http://www.evosuite.org/ ) if you scroll down, there are some interesting papers and documents you may want to look at.

**Comment by shenhuang** [comment]
Oops I had multiple post because GitHub was not working.

**Pull request merged**
