### PR TITLE
Automated test cases generated for method append.

### PR DESCRIPTION
**Pull request by LuanTa-CSUN**
1. Wrote automated tests generated for method append.
2. Ran tests.
3. Exported test result.

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @areeba-waheed

**Comment by kyledewey** [comment]
Additionally assigned @PatGarza20

**Review by PatGarza20 — APPROVED** [review]
All three of the tests appear to be clearly written and understandable. From what I gather they're intended to test appending strings together through append() vs simply adding one string to another, with the intention of them being equal. The string's content is also randomly generated so as to ensure that the method works with a variety of lengths. Great work overall!

**Review by areeba-waheed — APPROVED** [review]
Some comments would be nice. Otherwise good job!

**Pull request merged**
